sudo: required 
services: 
  - docker

before_install: 
  - docker build -t docron/docker-react-projects  -f Dockerfile.dev .

script:
  - docker run -e CI=true docron/docker-react-projects npm run test




deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-541263489771"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY"  