sudo: required 
services: 
  - docker

before_install: 
  - docker build -t docron/docker-react-projects  -f Dockerfile.dev .

  script:
    - docker run -e CI=true docron/docker-react-projects npm run test